<?php
/**
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2016
 *
 * @link      https://www.github.com/janhuang
 * @link      http://www.fast-d.cn/
 */

namespace FastD\Console\Tests\Input;

use FastD\Console\Input\InputDefinition;

class DemoDefinition extends InputDefinition
{
    public function getDefaultInputArguments()
    {
        return parent::getDefaultInputArguments(); // TODO: Change the autogenerated stub
    }

    public function getDefaultInputOptions()
    {
        return parent::getDefaultInputOptions(); // TODO: Change the autogenerated stub
    }
}